# Generated by Django 4.1.9 on 2023-06-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="user_id",
        ),
        migrations.AddField(
            model_name="feed",
            name="email",
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
