# Generated by Django 4.1.9 on 2023-06-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("profile_image", models.TextField()),
                ("nickname", models.CharField(max_length=24)),
                ("name", models.CharField(max_length=24)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "db_table": "User",
            },
        ),
        migrations.AlterField(
            model_name="feed",
            name="like_count",
            field=models.IntegerField(),
        ),
    ]
