# Generated by Django 4.1.9 on 2023-06-07 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_user_alter_feed_like_count"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
