# Generated by Django 4.1.9 on 2023-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_remove_feed_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="nickname",
            field=models.TextField(default="", max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="profile_image",
            field=models.TextField(default="default_profile.jpg"),
        ),
    ]
