# Generated by Django 4.1.9 on 2023-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_feed_nickname_feed_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="nickname",
            field=models.TextField(default="", max_length=24),
        ),
    ]
